baseurl = "/"
languageCode = "en"
theme = "terminal"
paginate = "4"

[params]
contentTypeName = "vfsdvdfsv"
themeColor = "orange"
fullWidthTheme = true
centerTheme = true
showMenuItems = "4"

[languages]

[languages.en]
title = "fdsvsdfsd"
subtitle = "dfsdfsd"
menuMore = "dsvdsfsdf"
readMore = "dsfsdfsd"
readOtherPosts = "dsfdsfsd"

[languages.en.params]

[languages.en.params.logo]
logoText = "fdsvdsv sf"
logoHomeLink = "dsfsdfdsfsd"

[languages.en.menu]

[[languages.en.menu.main]]
identifier = "ddfdsfds"
name = "dsfsdfsd"
url = "/fdsfsd/"

[[languages.en.menu.main]]
identifier = "dsfdsfsdfs"
name = "dsfsdfs"
url = "/43ufndsjv/"