backend:
  name: git-gateway
  branch: main
media_folder: static/media
public_folder: /media
site_url: https://hugo.mcchr.org
display_url: https://hugo.mcchr.org
collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
    sortable_fields: ['title', 'date']
  - name: 'pages'
    label: 'Pages'
    folder: 'content'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Aliases', name: 'aliases', widget: 'list' }
    sortable_fields: ['title', 'date']