backend:
  name: github
  repo: pusatrakyatlb/mcchr.org
  branch: main
media_folder: static/media
public_folder: /media
site_url: https://hugo.mcchr.org
display_url: https://hugo.mcchr.org
collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'content'
    filter:
      field: type
      value: post
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Type'
        name: 'type'
        widget: 'hidden'
        default: 'post'
      - label: 'Title' 
        name: 'title' 
        widget: 'string'
      - label: 'Cover Image'
        name: 'cover'
        widget: 'image'
        required: false
      - label: 'Body'
        name: 'body' 
        widget: 'markdown'
      - label: 'Tags'
        name: 'tag'
        widget: 'select'
        multiple: true
        options:
          - { label: 'Civic Education', value: 'education' }
          - { label: 'Strategic Litigation', value: 'litigation' }
          - { label: 'Law & Policy Reform', value: 'reform' }
        required: false
      - label: 'Category'
        name: 'category'
        widget: 'select'
        options:
          - { label: 'MCCHR Updates', value: 'updates' }
          - { label: 'MCCHR Campaigns', value: 'campaigns' }
          - { label: 'MCCHR Events', value: 'events' }
          - { label: 'MCCHR Training', value: 'training' }
          - { label: 'MCCHR Publications', value: 'publications' }
          - { label: 'MCCHR Merchandise', value: 'merchandise' }
          - { label: 'Human Rights News', value: 'news' }
        required: false
      - label: 'Date & Time'
        name: 'date'
        widget: 'datetime'
      - label: 'HTML Meta Description'
        name: 'description'
        widget: 'string'
        required: false
      - label: 'HTML Meta Keywords'
        name: 'keywords'
        widget: 'list'
        required: false
    sortable_fields: 
      - title
      - date
  - name: 'sections'
    label: 'Sections'
    label_singular: 'Section'
    folder: 'content'
    filter:
      field: type
      value: section
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Type'
        name: 'type'
        widget: 'hidden'
        default: 'section'
      - label: 'Title'
        name: 'title' 
        widget: 'string'
      - label: 'Cover Image'
        name: 'cover'
        widget: 'image'
        required: false
      - label: 'Body'
        name: 'body' 
        widget: 'markdown'
        required: false
      - label: 'Aliases'
        name: 'aliases'
        widget: 'list'
      - label: 'HTML Meta Description'
        name: 'description'
        widget: 'string'
        required: false
      - label: 'HTML Meta Keywords'
        name: 'keywords'
        widget: 'list'
        required: false
    sortable_fields: 
      - title
      - date
  - name: 'redirects'
    label: 'Redirects'
    label_singular: 'redirect'
    folder: 'content'
    filter:
      field: type
      value: redirect
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Type'
        name: 'type'
        widget: 'hidden'
        default: 'redirect'
      - label: 'Target URL'
        name: 'redirect' 
        widget: 'string'
        hint: 'To what URL do you want to redirect?'
      - label: 'Source Path'
        name: 'title' 
        widget: 'string'
        pattern: ['^[a-zA-Z0-9_.-]*$', 'Letters and numbers only']
        hint: 'What is the path on mcchr.org do you want to use for this redirect?'
    sortable_fields: 
      - title
      - date