backend:
  name: github
  repo: pusatrakyatlb/mcchr.org
  branch: main
media_folder: static/media
public_folder: /media
site_url: https://hugo.mcchr.org
display_url: https://hugo.mcchr.org
collections:
  - name: 'posts'
    label: 'Blog Posts'
    label_singular: 'Blog Post'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Title' 
        name: 'title' 
        widget: 'string'
      - label: 'Cover Image'
        name: 'cover'
        widget: 'image'
        required: false
      - label: 'Body'
        name: 'body' 
        widget: 'markdown'
      - label: 'Description'
        name: 'description'
        widget: 'string'
        required: false
      - label: 'Keywords'
        name: 'keywords'
        widget: 'list'
      - label: 'Date & Time'
        name: 'date'
        widget: 'datetime'
      - label: 'Tags'
        name: 'tag'
        widget: 'select'
        multiple: true
        options:
          - { label: 'Civic Education', value: 'education' }
          - { label: 'Strategic Litigation', value: 'litigation' }
          - { label: 'Law & Policy Reform', value: 'reform' }
      - label: 'Category'
        name: 'category'
        widget: 'select'
        options:
          - { label: 'MCCHR Updates', value: 'updates' }
          - { label: 'MCCHR Events', value: 'events' }
          - { label: 'MCCHR Publications', value: 'publications' }
          - { label: 'MCCHR Campaigns', value: 'campaigns' }
          - { label: 'Human Rights News', value: 'news' }
    sortable_fields: 
      - title
      - date
  - name: 'sections'
    label: 'Content Sections'
    label_singular: 'Content Section'
    folder: 'content'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Title'
        name: 'title' 
        widget: 'string'
      - label: 'Cover Image'
        name: 'cover'
        widget: 'image'
        required: false
      - label: 'Body'
        name: 'body' 
        widget: 'markdown'
        required: false
      - label: 'Description'
        name: 'description'
        widget: 'string'
      - label: 'Keywords'
        name: 'keywords'
        widget: 'list'
        required: false
      - label: 'Date & Time'
        name: 'date'
        widget: 'datetime'
      - label: 'Aliases'
        name: 'aliases'
        widget: 'list'
    sortable_fields: 
      - title
      - date