backend:
  name: github
  repo: pusatrakyatlb/mcchr.org
  branch: main
media_folder: static/media
public_folder: /media
site_url: https://hugo.mcchr.org
display_url: https://hugo.mcchr.org
collections:
  - name: 'posts'
    label: 'Content Posts'
    label_singular: 'Content Post'
    folder: 'content'
    filter:
      field: type
      value: post
    create: true
    slug: '{{year}}{{month}}{{day}}-{{slug}}'
    preview_path: '{{filename}}'
    editor:
      preview: false
    show_preview_links: true
    fields:
      - label: 'Type'
        name: 'type'
        widget: 'hidden'
        default: 'post'
      - label: 'Title' 
        name: 'title' 
        widget: 'string'
      - label: 'Cover Image'
        name: 'cover'
        widget: 'image'
        required: false
      - label: 'Body'
        name: 'body' 
        widget: 'markdown'
      - label: 'Tags'
        name: 'tag'
        widget: 'select'
        multiple: true
        options:
          - { label: 'Civic Education', value: 'education' }
          - { label: 'Strategic Litigation', value: 'litigation' }
          - { label: 'Law & Policy Reform', value: 'reform' }
        required: false
      - label: 'Category'
        name: 'category'
        widget: 'select'
        options:
          - { label: 'MCCHR Updates', value: 'updates' }
          - { label: 'MCCHR Campaigns', value: 'campaigns' }
          - { label: 'MCCHR Events', value: 'events' }
          - { label: 'MCCHR Training', value: 'training' }
          - { label: 'MCCHR Publications', value: 'publications' }
          - { label: 'MCCHR Merchandise', value: 'merchandise' }
          - { label: 'Human Rights News', value: 'news' }
        required: false
      - label: 'Date & Time'
        name: 'date'
        widget: 'datetime'
      - label: 'Aliases'
        name: 'aliases'
        widget: 'list'
      - label: 'HTML Meta Description'
        name: 'description'
        widget: 'string'
        required: false
      - label: 'HTML Meta Keywords'
        name: 'keywords'
        widget: 'list'
        required: false
    sortable_fields: 
      - title
      - date
    view_filters:
      - label: "Civic Education"
        field: tag
        pattern: 'education'
      - label: 'Strategic Litigation'
        field: tag
        pattern: 'litigation'
      - label: 'Law & Policy Reform'
        field: tag
        pattern: 'reform'
      - label: 'MCCHR Updates'
        field: category
        pattern: 'updates'
      - label: 'MCCHR Campaigns'
        field: category
        pattern: 'campaigns'
      - label: 'MCCHR Events'
        field: category
        pattern: 'events'
      - label: 'MCCHR Training'
        field: category
        pattern: 'training'
      - label: 'MCCHR Publications'
        field: category
        pattern: 'publications'
      - label: 'MCCHR Merchandise'
        field: category
        pattern: 'merchandise'
      - label: 'Human Rights News'
        field: category
        pattern: 'news'
  - name: 'sections'
    label: 'Content Sections'
    label_singular: 'Content Section'
    folder: 'content'
    filter:
      field: type
      value: section
    create: true
    slug: '{{slug}}'
    preview_path: '{{filename}}'
    editor:
      preview: false
    show_preview_links: true
    fields:
      - label: 'Type'
        name: 'type'
        widget: 'hidden'
        default: 'section'
      - label: 'Title'
        name: 'title' 
        widget: 'string'
      - label: 'Cover Image'
        name: 'cover'
        widget: 'image'
        required: false
      - label: 'Body'
        name: 'body' 
        widget: 'markdown'
        required: false
      - label: 'Aliases'
        name: 'aliases'
        widget: 'list'
      - label: 'HTML Meta Description'
        name: 'description'
        widget: 'string'
        required: false
      - label: 'HTML Meta Keywords'
        name: 'keywords'
        widget: 'list'
        required: false
    sortable_fields: 
      - title
      - date
  - name: 'redirects'
    label: 'URL Redirects'
    label_singular: 'URL Redirect'
    folder: 'content'
    filter:
      field: type
      value: redirect
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    show_preview_links: false
    search: false
    fields:
      - label: 'Type'
        name: 'type'
        widget: 'hidden'
        default: 'redirect'
      - label: 'Source Path'
        name: 'title' 
        widget: 'string'
        pattern: ['^[a-zA-Z0-9_.-]*$', 'Letters and numbers only']
        hint: 'What is the path on that do you want to use?'
      - label: 'Target URL'
        name: 'redirect' 
        widget: 'string'
        hint: 'To what URL do you want to redirect?'
    sortable_fields: 
      - title
      - date
  - name: 'config'
    label: 'Site Configurations'
    editor:
      preview: false
    show_preview_links: false
    search: false
    files:
      - label: "General Configurations"
        name: "general"
        file: 'config.toml'
        fields:
          - label: 'Base URL'
            name: 'baseurl'
            widget: 'hidden'
            default: '/'
          - label: 'Default Language'
            name: 'languageCode'
            widget: 'string'
            default: 'en'
          - label: 'Theme'
            name: 'theme'
            widget: 'string'
          - label: 'Pagination'
            name: 'paginate'
            widget: 'string'
            default: 20
            pattern: ['^[1-9]\d*$', 'Integer more than zero']
          - label: 'Parameters'
            name: 'params'
            widget: 'object'
            fields: 
              - label: 'Content Type'
                name: 'contentTypeName'
                widget: 'string'
                default: 'posts'
              - label: 'Theme Colour'
                name: 'themeColor'
                widget: 'string'
                default: 'orange'
              - label: 'Show Menu Items'
                name: 'showMenuItems'
                widget: 'string'
                default: 2
                pattern: ['^[1-9]\d*$', 'Integer more than zero']
              - label: 'fullWidthTheme'
                name: 'fullWidthTheme'
                widget: 'boolean'
                default: true
              - label: 'centerTheme'
                name: 'centerTheme'
                widget: 'boolean'
                default: true
          - label: 'Localization'
            name: 'languages'
            widget: 'object'
            fields: 
              - label: 'English'
                name: 'en'
                widget: 'object'
                fields: 
                  - label: 'Site Title'
                    name: 'title'
                    widget: 'string'
                    default: 'Terminal'
                  - label: 'Site Tagline'
                    name: 'subtitle'
                    widget: 'string'
                    default: 'A simple, retro theme for Hugo'
                  - label: 'Keywords'
                    name: 'keywords'
                    widget: 'string'
                    required: false
                  - label: 'Copyright Statement'
                    name: 'copyright'
                    widget: 'string'
                    required: false
                  - label: 'Label for Show More Menu'
                    name: 'menuMore'
                    widget: 'string'
                    default: 'Show more'
                  - label: 'Label for Read More Content'
                    name: 'readMore'
                    widget: 'string'
                    default: 'Read more'
                  - label: 'Label for Read Other Content'
                    name: 'readOtherPosts'
                    widget: 'string'
                    default: 'Read other posts'
                  - label: 'Parameters'
                    name: 'params'
                    widget: 'object'
                    fields: 
                      - label: 'Logo'
                        name: 'logo'
                        widget: 'object'
                        fields: 
                          - label: 'Logo Text'
                            name: 'logoText'
                            widget: 'string'
                            default: 'Terminal'
                          - label: 'Logo Home Link'
                            name: 'logoHomeLink'
                            widget: 'string'
                            default: '/'
                  - label: 'Menus'
                    name: 'menu'
                    widget: 'object'
                    fields: 
                      - label: 'Main Menu'
                        name: 'main'
                        widget: 'list'
                        summary: '{{fields.name}} - {{fields.url}}'
                        fields:
                          - label: 'identifier'
                            name: 'identifier'
                            widget: 'string'
                          - label: 'name'
                            name: 'name'
                            widget: 'string'
                          - label: 'url'
                            name: 'url'
                            widget: 'string'